config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#show"
  resources :frames, only: [:show] do
    resources :reflections, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :frame
end

app/models/reflection.rb
class Reflection < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.slim
nav.navbar role="navigation"
  div.navbar-brand
    h1*{ class: "navbar-item has-text-primary" } Tiniich
    div.navbar-burger
      span
      span
      span
  div.navbar-menu
    div.navbar-start
      a.navbar-item href="/" Home
      a.navbar-item href="/about" About
      a.navbar-item href="/love" Share Love

app/views/home/show.html.slim
section.container
  h1.page-title Help Derrick Reflect
  p.content
    = t(".context")
  p.content
    = t(".feedback").html_safe
  div
    = link_to t(".button"), new_frame_reflection_path(Frame.first.id), class: "button is-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiniich</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "navigation" %>
    <%= yield %>
  </body>
</html>

app/views/reflections/new.html.slim
section.container
  h2.page-title
    = t(".title")
    = raise